#!/run/current-system/sw/bin/bash
OBJECT="$1"
OPERATION="$2"
SUBOPERATION="$3"

BASEDIR="$(dirname "$0")"
HOOKPATH="$BASEDIR/qemu.d/$OBJECT/$OPERATION/$SUBOPERATION"

if [ -f "$HOOKPATH" ]; then
  eval \""$HOOKPATH"\" "$@"
fi
