# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ ... }:

{
  flake.nixosModules.aegisHardware =

    {
      config,
      lib,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/enc";
        fsType = "btrfs";
        options = [
          "subvol=root"
          "compress=zstd"
          "noatime"
        ];
      };

      boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/4a075449-ca66-43e9-8c4a-936f1ca8b5ef";

      fileSystems."/nix" = {
        device = "/dev/mapper/enc";
        fsType = "btrfs";
        options = [
          "subvol=nix"
          "compress=zstd"
          "noatime"
        ];
      };

      fileSystems."/var/log" = {
        device = "/dev/mapper/enc";
        fsType = "btrfs";
        options = [
          "subvol=log"
          "compress=zstd"
          "noatime"
        ];
        neededForBoot = true;
      };

      fileSystems."/persist" = {
        device = "/dev/mapper/enc";
        fsType = "btrfs";
        options = [
          "subvol=persist"
          "compress=zstd"
          "noatime"
        ];
        neededForBoot = true;
      };

      fileSystems."/home" = {
        device = "/dev/mapper/enc";
        fsType = "btrfs";
        options = [
          "subvol=home"
          "compress=zstd"
          "noatime"
        ];
      };

      fileSystems."/swap" = {
        device = "/dev/mapper/enc";
        fsType = "btrfs";
        options = [
          "subvol=swap"
          "compress=zstd"
          "noatime"
        ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/45D7-A378";
        fsType = "vfat";
        options = [
          "fmask=0177"
          "dmask=0077"
        ];
      };

      swapDevices = [
        {
          device = "/swap/swapfile";
          size = 8 * 1024; # 8GiB
        }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
